server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: funds
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://db:5432/funds_db
    username: pguser
    password: pgpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/swagger-ui.html

logging:
  level:
    com.atait.assignment: DEBUG
